### ISSUE TITLE
Fails on symlinks

### ISSUE THREAD

**Issue by RubenVerborgh** [SonarSource/SonarJS#1057]
**SonarJS version:** 1.0.0<br>
**Reproducer** 
Have a symlink somewhere on the path

**Expected behavior**
The symlink is handled properly

Instead, this happens:

```
java.lang.IllegalStateException: Fail to read file '/home/travis/build/solid/node-solid-server/test/resources/config/templates' with encoding 'UTF-8'
- Analyzing /home/travis/build/solid/node-solid-server

Caused by: java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read(BufferedReader.java:182)
	at org.sonarsource.sonarlint.core.container.analysis.filesystem.FileMetadata.read(FileMetadata.java:170)
	at org.sonarsource.sonarlint.core.container.analysis.filesystem.FileMetadata.readMetadata(FileMetadata.java:152)
	... 17 more
```

**Example**
https://travis-ci.org/solid/node-solid-server/jobs/425017110

**Comment by RubenVerborgh** [comment]
Ignoring symlinked paths with `-e`  doesn't work either.

**Comment by vilchik-elena** [comment]
https://github.com/SonarSource/sonarjs-cli is deprecated.
You eslint or tslint extentions: 
https://www.npmjs.com/package/eslint-plugin-sonarjs
https://www.npmjs.com/package/tslint-sonarts

**Comment by RubenVerborgh** [comment]
@vilchik-elena Can you mark the npm package as deprecated in that case?

**Comment by vilchik-elena** [comment]
@RubenVerborgh I failed to find how to do it properly (I found how to deprecate the version but not entire package). Do you know?

**Comment by RubenVerborgh** [comment]
Deprecating the latest version should be enough; that’s what you usually get when installing.
Could you include the above information in the deprecation message? Thanks.
