### ISSUE TITLE
eslint-bridge: Failed to start server

### ISSUE THREAD

**Issue by kpersohn** [SonarSource/SonarJS#1228]
Any ideas why eslint-bridge would fail to start or where I can get more detailed logging to see the cause? 

**I want to report a bug.**

**SonarJS version:** 5.0.0.6962
**SonarQube version:** 7.1.0.11001

**Logs**
```
INFO: Using default Node.js executable: 'node'.
ERROR: Failure during analysis, Node.js command to start eslint-bridge was: node /builds/lvhub/ms-app-pending-v2/.scannerwork/.sonartmp/eslint-bridge-bundle/node_modules/eslint-bridge/bin/server 37046
java.lang.IllegalStateException: Failed to start server (10s timeout)
	at org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl.startServer(EslintBridgeServerImpl.java:119)
	at org.sonar.plugins.javascript.eslint.EslintBasedRulesSensor.execute(EslintBasedRulesSensor.java:81)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:302)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:297)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:271)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**Comment by vilchik-elena** [comment]
Could you provide debug logs? (run command with `-X`) 
Also try to execute command mentioned in error message:  `/builds/lvhub/ms-app-pending-v2/.scannerwork/.sonartmp/eslint-bridge-bundle/node_modules/eslint-bridge/bin/server 37046`

**Comment by cjrobbertse** [comment]
this is my command: `node /Users/cjrobbertse/Vodafone Group/Christopher Robbertse - Documents/AVTS (Active Validation Test Suite)/VFGroup-APITestEngine-StaticCTK/.scannerwork/.sonartmp/eslint-bridge-bundle/node_modules/eslint-bridge/bin/server 53145`

heres the exeption: ```bash: syntax error near unexpected token `('```

looks like it doesnt understand the spaces and brackets in the path.

**Comment by vilchik-elena** [comment]
closing. Please start a new thread https://community.sonarsource.com/ if problem remains
