### ISSUE TITLE
ClassCastException: org.sonar.javascript.tree.impl.expression.IdentifierTreeImpl cannot be cast to org.sonar.plugins.javascript.api.tree.expression.LiteralTree

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#1598]
Analysis of ag-grid is failing with following stacktrace

possibly related to #1402 

```
ERROR: Unable to analyse file: file:///tmp/cirrus-ci-build/ag-grid/workspace/packages/ag-grid-enterprise/dist/lib/charts/chart/series/barSeries.js
java.lang.ClassCastException: org.sonar.javascript.tree.impl.expression.IdentifierTreeImpl cannot be cast to org.sonar.plugins.javascript.api.tree.expression.LiteralTree
    at org.sonar.javascript.checks.DeadStoreCheck.isBasicValue(DeadStoreCheck.java:179)
    at org.sonar.javascript.checks.DeadStoreCheck.initializedToBasicValue(DeadStoreCheck.java:167)
    at org.sonar.javascript.checks.DeadStoreCheck.checkUsage(DeadStoreCheck.java:150)
    at org.sonar.javascript.checks.DeadStoreCheck.checkCFG(DeadStoreCheck.java:127)
    at org.sonar.javascript.checks.DeadStoreCheck.checkFunction(DeadStoreCheck.java:102)
    at org.sonar.javascript.checks.DeadStoreCheck.visitFunctionExpression(DeadStoreCheck.java:75)
    at org.sonar.javascript.tree.impl.expression.FunctionExpressionTreeImpl.accept(FunctionExpressionTreeImpl.java:151)
    at org.sonar.plugins.javascript.api.visitors.DoubleDispatchVisitor.scanChildren(DoubleDispatchVisitor.java:192)
    at org.sonar.plugins.javascript.api.visitors.DoubleDispatchVisitor.visitAssignmentExpression(DoubleDispatchVisitor.java:422)
    at org.sonar.javascript.tree.impl.expression.AssignmentExpressionTreeImpl.accept(AssignmentExpressionTr
```

**Comment by saberduck** [comment]
in fact, it really is duplicate of #1402
