### ISSUE TITLE
On OSX, '/bin/sh -c node -v' fails

### ISSUE THREAD

**Issue by Epithumia** [SonarSource/SonarJS#1674]
**I want to report a bug.**

On OSX, '/bin/sh -c node -v' fails because it actually runs node (v10.15.0) in interactive mode instead of getting the version number.

**SonarJS version:** 
5.1.1 (build 7506)

**Logs**
```
INFO 16:54:24.163 > INFO: Sensor ESLint-based SonarJS [javascript]
ERROR 16:54:26.997 > ERROR: /bin/sh: node: command not found
ERROR 16:54:26.999 > ERROR: Failed to determine the version of Node.js, exit value 127. Executed: '/bin/sh -c node -v'
ERROR 16:54:26.999 > org.sonarsource.nodejs.NodeCommandException: Failed to determine the version of Node.js, exit value 127. Executed: '/bin/sh -c node -v'
ERROR 16:54:26.999 > 	at org.sonarsource.nodejs.NodeCommandBuilderImpl.getVersion(NodeCommandBuilderImpl.java:174)
INFO 16:54:26.999 > INFO: Sensor ESLint-based SonarJS [javascript] (done) | time=2836ms
ERROR 16:54:26.999 > 	at org.sonarsource.nodejs.NodeCommandBuilderImpl.checkNodeCompatibility(NodeCommandBuilderImpl.java:144)
ERROR 16:54:26.999 > 	at org.sonarsource.nodejs.NodeCommandBuilderImpl.build(NodeCommandBuilderImpl.java:120)
ERROR 16:54:27.000 > 	at org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl.initNodeCommand(EslintBridgeServerImpl.java:129)
ERROR 16:54:27.000 > 	at org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl.startServer(EslintBridgeServerImpl.java:105)
ERROR 16:54:27.000 > 	at org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl.startServerLazily(EslintBridgeServerImpl.java:145)
ERROR 16:54:27.000 > 	at org.sonar.plugins.javascript.eslint.EslintBasedRulesSensor.execute(EslintBasedRulesSensor.java:92)
ERROR 16:54:27.000 > 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
ERROR 16:54:27.000 > 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
ERROR 16:54:27.000 > 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
ERROR 16:54:27.000 > 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
ERROR 16:54:27.000 > 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
ERROR 16:54:27.000 > 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
ERROR 16:54:27.000 > 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
ERROR 16:54:27.000 > 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
ERROR 16:54:27.000 > 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:302)
ERROR 16:54:27.000 > 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:297)
ERROR 16:54:27.000 > 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:271)
ERROR 16:54:27.000 > 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
ERROR 16:54:27.000 > 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
ERROR 16:54:27.000 > 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
ERROR 16:54:27.000 > 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
ERROR 16:54:27.000 > 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
ERROR 16:54:27.000 > 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
ERROR 16:54:27.000 > 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
ERROR 16:54:27.000 > 	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
ERROR 16:54:27.000 > 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
ERROR 16:54:27.000 > 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
ERROR 16:54:27.000 > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ERROR 16:54:27.000 > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
ERROR 16:54:27.000 > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
ERROR 16:54:27.000 > 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
ERROR 16:54:27.000 > 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
ERROR 16:54:27.000 > 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
ERROR 16:54:27.000 > 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
INFO 16:54:27.000 > INFO: Sensor SonarJavaXmlFileSensor [java]
ERROR 16:54:27.000 > 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
ERROR 16:54:27.000 > 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
ERROR 16:54:27.000 > 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
ERROR 16:54:27.000 > 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**Expected behavior**
I expect it to actually run ;)
```/bin/sh -c 'node -v'``` should work.

**Comment by saberduck** [comment]
hello @Epithumia , from this log line
```ERROR 16:54:26.997 > ERROR: /bin/sh: node: command not found```
it seems that node is not on the path when scanner is executed. Can you verify that node is indeed available for the scanner process? Maybe `PATH` variable is modified somewhere?

**Comment by Epithumia** [comment]
Scanner is called from a script, itself called by PyCharm. After investigating, it turns out my $PATH was overwritten, so adding it back at the start of the script fixed the issue.
