### ISSUE TITLE
Updating the plugin to version 6.1 would crash the server

### ISSUE THREAD

**Issue by sesto** [SonarSource/SonarJS#1760]
When I try to update the plugin to the latest version the server crashes
**SonarJS version:** 6.1<br>
**SonarQube version:** 7.9.1-community<br>
**SonarLint version:** <br>
**Logs**
```
ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Rule with key 'javascript:VariableDeclarationAfterUsage' not found
```

**Expected behavior**

**Comment by vilchik-elena** [comment]
@sesto do you have a full stacktrace? 

What was the previous version of SonarJS?
Did you upgrade through marketplace?

**Comment by sesto** [comment]
The previous version is: 5.2.1 (build 7778)
The upgrade is done via the marketplace
The full stack trace
```
2019.11.20 08:40:56 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Rule with key 'javascript:VariableDeclarationAfterUsage' not found
	at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.lambda$updateOrCreateBuilder$5(BuiltInQProfileRepositoryImpl.java:188)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Unknown Source)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.updateOrCreateBuilder(BuiltInQProfileRepositoryImpl.java:185)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.lambda$toQualityProfileBuilders$4(BuiltInQProfileRepositoryImpl.java:164)
	at java.base/java.util.HashMap.compute(Unknown Source)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.toQualityProfileBuilders(BuiltInQProfileRepositoryImpl.java:162)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.lambda$toFlatList$2(BuiltInQProfileRepositoryImpl.java:133)
	at org.sonar.core.util.stream.MoreCollectors.lambda$uniqueIndex$9(MoreCollectors.java:258)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.toFlatList(BuiltInQProfileRepositoryImpl.java:131)
	at org.sonar.server.qualityprofile.BuiltInQProfileRepositoryImpl.initialize(BuiltInQProfileRepositoryImpl.java:81)
	at org.sonar.server.qualityprofile.BuiltInQProfileLoader.start(BuiltInQProfileLoader.java:37)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:47)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:83)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:46)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:80)
	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:196)
	at org.sonar.server.platform.Platform.access$400(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$1(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by vilchik-elena** [comment]
@sesto We still can't reproduce and get to the root problem. Could you provide more info to help us?
* what are the profiles you have for JavaScript?
* which DB are you using?
* do you have that rule activated in custom profiles (by default it's in "Sonar way Recommended" profile)? do you have issues for this rule? 

We migrated this rule key between 5.2 and 6.1 SonarJS versions (new rule key is `javascript:S1526`), and obviously something went wrong, but we can't get what exactly

**Comment by sesto** [comment]
Apparently, another plugin from https://www.codescan.io/ is using this rule. This was the problem. Until that plugin is not upgraded to use the new rule key, we cannot upgrade this one.
As the things cleared out, I am closing the issue

**Comment by saberduck** [comment]
@sesto , in fact, this is something SonarQube should be able to handle. We created a ticket to fix it https://jira.sonarsource.com/browse/SONAR-12736 
Thanks for reporting the problem!
