### ISSUE TITLE
getTypeScriptLocation selects unwanted version of typescript from subdirectories

### ISSUE THREAD

**Issue by mdonoughe** [SonarSource/SonarJS#1964]
**I want to report a bug.**

**SonarJS version:** 6.1.0.11505<br>

**Reproducer** 

Create a Typescript project having a dev-dependency on @angular-devkit/build-angular 0.11.4 (used by Angular CLI 7.3.3?) and a supported version of Typescript.

```
{
    "devDependencies": [
        "@angular-devkit/build-angular": "0.11.4",
        "typescript": "3.2.4"
    ]
}
```

When you restore packages, typescript 3.2.4 will be placed into node_modules, but @angular-devkit/build-angular 0.11.4 depends on @angular-devkit/build-optimizer 0.11.4 which will restore its own, private copy of typescript 3.1.6 into node_modules/@angular-devkit/build-optimizer/node_modules.

When you try to run SonarJS, [`EslintBridgeServerImpl.getTypeScriptLocation`](https://github.com/SonarSource/SonarJS/blob/8c6d6bd809b861a63dbace8011360e32bffe7825/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java#L319) does apparently, at least on Windows, a depth-first, alphabetical, recursive search for the first typescript it finds. In this case, because "@angular-devkit" comes before "typescript", typescript 3.1.6 (incompatible with SonarJS) is loaded from node_modules/@angular-devkit/build-optimizer/node_modules instead of typescript 3.2.4 from node_modules.

**Logs**
```
15:48:31.827 INFO: Sensor JavaScript analysis [javascript]
15:48:31.827 DEBUG: Deploying bundle
15:48:31.827 DEBUG: Deploying eslint-bridge into C:\build-dir\RootProject\.sonarqube\out\.sonar\.sonartmp\eslint-bridge-bundle
15:48:38.437 DEBUG: Deploying bundle (done) | time=6610ms
15:48:38.437 DEBUG: Starting server
15:48:38.437 DEBUG: Looking for TypeScript recursively in C:\build-dir\RootProject\ChildProject\App
15:48:43.984 INFO: Using TypeScript at: 'C:\build-dir\RootProject\ChildProject\App\node_modules\@angular-devkit\build-optimizer\node_modules'
15:48:43.984 INFO: Using Node.js executable C:\build-dir\RootProject\ChildProject\App\.gradle\nodejs\node-v10.16.0-win-x64\node.exe from property sonar.nodejs.executable.
15:48:43.984 DEBUG: Checking Node.js version
15:48:43.984 DEBUG: Launching command C:\build-dir\RootProject\ChildProject\App\.gradle\nodejs\node-v10.16.0-win-x64\node.exe -v
15:48:44.046 DEBUG: Using Node.js v10.16.0.
15:48:44.046 DEBUG: Starting Node.js process to start eslint-bridge server at port 63391
15:48:44.046 DEBUG: Launching command {NODE_PATH=C:\build-dir\RootProject\ChildProject\App\node_modules\@angular-devkit\build-optimizer\node_modules} C:\build-dir\RootProject\ChildProject\App\.gradle\nodejs\node-v10.16.0-win-x64\node.exe C:\build-dir\RootProject\.sonarqube\out\.sonar\.sonartmp\eslint-bridge-bundle\package\bin\server 63391
15:48:45.624 DEBUG: starting eslint-bridge server at port 63391
15:48:45.655 DEBUG: eslint-bridge server is running at port 63391
15:48:45.687 DEBUG: Starting server (done) | time=7250ms
15:48:45.687 INFO: 1 source files to be analyzed
15:48:45.859 INFO: 1/1 source files have been analyzed
15:48:45.859 INFO: Sensor SonarJS [javascript]
15:48:45.874 INFO: 1 source files to be analyzed
15:48:46.015 INFO: Sensor SonarJS [javascript] (done) | time=156ms
15:48:46.015 INFO: Sensor JavaScript analysis [javascript] (done) | time=14188ms
15:48:46.015 INFO: Sensor TypeScript analysis [javascript]
15:48:46.015 INFO: 1/1 source files have been analyzed
15:48:46.015 DEBUG: SonarJS eslint-bridge server is up, no need to start.
15:48:46.718 INFO: Found 1 tsconfig.json file(s): [C:\build-dir\RootProject\ChildProject\App\tsconfig.json]
15:48:46.812 DEBUG: C:/build-dir/RootProject/ChildProject/App/src/app/app.component.spec.ts matched C:\build-dir\RootProject\ChildProject\App\tsconfig.json
15:48:46.812 DEBUG: C:/build-dir/RootProject/ChildProject/App/src/app/app.component.ts matched C:\build-dir\RootProject\ChildProject\App\tsconfig.json
15:48:46.812 DEBUG: C:/build-dir/RootProject/ChildProject/App/src/app/app.module.ts matched C:\build-dir\RootProject\ChildProject\App\tsconfig.json
```
...
```
15:48:46.843 DEBUG: C:/build-dir/RootProject/ChildProject/App/src/test.ts matched C:\build-dir\RootProject\ChildProject\App\tsconfig.json
15:48:46.843 INFO: 207 source files to be analyzed
15:48:46.843 INFO: Analyzing 207 files using tsconfig: C:\build-dir\RootProject\ChildProject\App\tsconfig.json
15:48:46.859 DEBUG: 'ChildProject/App/src/app/app.component.spec.ts' generated metadata with charset 'UTF-8'
15:48:46.874 ERROR: You are using version of TypeScript 3.1.6 which is not supported; supported versions >=3.2.1
15:48:46.874 ERROR: If it's not possible to upgrade version of TypeScript used by the project, consider installing supported TypeScript version just for the time of analysis
15:48:46.905 ERROR: Failure during analysis, Node.js command to start eslint-bridge was: {NODE_PATH=C:\build-dir\RootProject\ChildProject\App\node_modules\@angular-devkit\build-optimizer\node_modules} C:\build-dir\RootProject\ChildProject\App\.gradle\nodejs\node-v10.16.0-win-x64\node.exe C:\build-dir\RootProject\.sonarqube\out\.sonar\.sonartmp\eslint-bridge-bundle\package\bin\server 63391
java.lang.IllegalStateException: Unsupported TypeScript version
        at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.processParsingError(AbstractEslintSensor.java:149)
        at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.processResponse(AbstractEslintSensor.java:188)
        at org.sonar.plugins.javascript.eslint.TypeScriptSensor.analyze(TypeScriptSensor.java:154)
        at org.sonar.plugins.javascript.eslint.TypeScriptSensor.analyzeFilesWithTsConfig(TypeScriptSensor.java:141)
15:48:46.905 INFO: Sensor TypeScript analysis [javascript] (done) | time=890ms
15:48:46.905 INFO: ------------- Run sensors on module HubRegistrator
        at org.sonar.plugins.javascript.eslint.TypeScriptSensor.analyzeFiles(TypeScriptSensor.java:121)
        at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.execute(AbstractEslintSensor.java:107)
        at org.sonar.plugins.javascript.eslint.TypeScriptSensor.execute(TypeScriptSensor.java:53)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:392)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**Expected behavior**

The search algorithm should take the supported typescript from the node_modules folder instead of searching deep into the node_modules folder to find an unsupported version. Either it shouldn't search recursively within node_modules folders or it should take the typescript closest to the root of the original node_modules folder.

**Comment by vilchik-elena** [comment]
Hi,

There is already ticket for that https://github.com/SonarSource/SonarJS/issues/1928
