### ISSUE TITLE
Insufficiently accurate exception message in case of IOException

### ISSUE THREAD

**Issue by tarexme** [SonarSource/SonarJS#1987]
**I want to report a bug.**
If a file cannot be found, the IllegalStateException is thrown. But the message contains `Unable to read file org.sonar.javascript.visitors.JavaScriptFileImpl@5a2bd7c8` instead of filename. 

You can find from stacktrace, which file cause the error, but the description of IllegalStateException is insufficiently accurate.

**SonarJS version:** 6.2.1
**SonarQube version:** 8.2<br>

**Reproducer** 
Run a check for a project with a file, that causes IOException. For me, it was an inaccessible symbolic link with `.js` extension.
```
// Directory listing
test.js -> test2.js // test2.js does not exists
```

**Logs**
```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to read file org.sonar.javascript.visitors.JavaScriptFileImpl@5a2bd7c8
	at org.sonar.javascript.checks.utils.CheckUtils.readLines(CheckUtils.java:138)
	at org.sonar.plugins.javascript.minify.AverageLineLengthCalculator.getAverageLineLength(AverageLineLengthCalculator.java:53)
	at org.sonar.plugins.javascript.minify.MinificationAssessor.hasExcessiveAverageLineLength(MinificationAssessor.java:66)
	at org.sonar.plugins.javascript.minify.MinificationAssessor.isMinified(MinificationAssessor.java:53)
	at org.sonar.plugins.javascript.JavaScriptExclusionsFileFilter.accept(JavaScriptExclusionsFileFilter.java:47)
	at org.sonar.scanner.scan.filesystem.FileIndexer.accept(FileIndexer.java:258)
	at org.sonar.scanner.scan.filesystem.FileIndexer.indexFile(FileIndexer.java:138)
	at org.sonar.scanner.scan.filesystem.ProjectFileIndexer$IndexFileVisitor.visitFile(ProjectFileIndexer.java:242)
	at org.sonar.scanner.scan.filesystem.ProjectFileIndexer$IndexFileVisitor.visitFile(ProjectFileIndexer.java:214)
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
	at org.sonar.scanner.scan.filesystem.ProjectFileIndexer.indexDirectory(ProjectFileIndexer.java:210)
	at org.sonar.scanner.scan.filesystem.ProjectFileIndexer.indexFiles(ProjectFileIndexer.java:197)
	at org.sonar.scanner.scan.filesystem.ProjectFileIndexer.index(ProjectFileIndexer.java:159)
	at org.sonar.scanner.scan.filesystem.ProjectFileIndexer.indexModulesRecursively(ProjectFileIndexer.java:138)
	at org.sonar.scanner.scan.filesystem.ProjectFileIndexer.index(ProjectFileIndexer.java:108)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:346)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.nio.file.NoSuchFileException: /Users/tarexme/TestProject/test.js
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
	at java.base/java.nio.file.Files.newInputStream(Unknown Source)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.inputStream(DefaultInputFile.java:98)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.contents(DefaultInputFile.java:108)
	at org.sonar.javascript.visitors.JavaScriptFileImpl.contents(JavaScriptFileImpl.java:42)
	at org.sonar.javascript.checks.utils.CheckUtils.newBufferedReader(CheckUtils.java:143)
	at org.sonar.javascript.checks.utils.CheckUtils.readLines(CheckUtils.java:134)
	... 34 more
```

**Expected behavior**
The message of IllegalStateException should contain the file path. For example: `java.lang.IllegalStateException: Unable to read file test.js`

**Comment by vilchik-elena** [comment]
Here https://github.com/SonarSource/SonarJS/blob/68fa2aa7d1664b2e7e3ce9185da1a65a39dedf31/javascript-checks/src/main/java/org/sonar/javascript/checks/utils/CheckUtils.java#L138 we should use `file.uri()`
