### ISSUE TITLE
Fails with TS 4.0.0-dev.20200629: TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#2018]
Fails during `parser.parseTypeScriptSourceFile` with TS 4.0.0-dev.20200629 on TypeScript project analysis (private repo link https://github.com/SonarSource/typescript-test-sources/blob/7fe0afbd00a102d2fe0466f7ffd48a180c419689/src/TypeScript/src/compiler/checker.ts)
```
WARN: TypeError: Cannot read property 'map' of undefined
INFO:     at Converter.convertNode (.../SonarJS/its/typescript-test-sources/src/TypeScript/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:2089:53)
INFO:     at Converter.converter (.../SonarJS/its/typescript-test-sources/src/TypeScript/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:72:29)
INFO:     at Converter.convertType (.../SonarJS/its/typescript-test-sources/src/TypeScript/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:156:21)
INFO:     at Converter.convertTypeAnnotation (.../SonarJS/its/typescript-test-sources/src/TypeScript/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:190:34)
INFO:     at Converter.convertNode (.../SonarJS/its/typescript-test-sources/src/TypeScript/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:591:46)
INFO:     at Converter.converter (.../SonarJS/its/typescript-test-sources/src/TypeScript/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:72:29)
INFO:     at Converter.convertChild (.../SonarJS/its/typescript-test-sources/src/TypeScript/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:147:21)
INFO:     at nodes.map.statement (.../SonarJS/its/typescript-test-sources/src/TypeScript/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:203:32)
INFO:     at Array.map (<anonymous>)
INFO:     at Converter.convertBodyExpressions (.../SonarJS/its/typescript-test-sources/src/TypeScript/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/@typescript-eslint/typescript-estree/dist/convert.js:202:14)

```

**Comment by saberduck** [comment]
This was fixed in #2013 by packaging typescript in the plugin
