### ISSUE TITLE
SonarQube is very slow and fails with out of memory exception

### ISSUE THREAD

**Issue by kirill-konshin** [SonarSource/SonarJS#2040]
I am using SQ with Yarn 2 in pnp mode, and here's the output

```
INFO: Scanner configuration file: /opt/sonar-scanner-4.1.0.1829-linux/conf/sonar-scanner.properties
 INFO: Project root configuration file: /builds/web/web/sonar-project.properties
 INFO: SonarQube Scanner 4.1.0.1829
 INFO: Java 13 Oracle Corporation (64-bit)
 INFO: Linux 3.10.0-1062.1.1.el7.x86_64 amd64
 INFO: User cache: /builds/web/web/.sonar/cache
 INFO: SonarQube server 8.2.0
 INFO: Default locale: "en_US", source code encoding: "UTF-8"
 INFO: Load global settings
 INFO: Load global settings (done) | time=123ms
 INFO: Server id: XXX
 INFO: User cache: /builds/web/web/.sonar/cache
 INFO: Load/download plugins
 INFO: Load plugins index
 INFO: Load plugins index (done) | time=43ms
 INFO: Load/download plugins (done) | time=127ms
 INFO: Process project properties
 INFO: Process project properties (done) | time=8ms
 INFO: Execute project builders
 INFO: Execute project builders (done) | time=4ms
 INFO: Project key: serviceweb-scs
 INFO: Base dir: /builds/web/web
 INFO: Working dir: /builds/web/web/.scannerwork
 INFO: Load project settings for component key: 'serviceweb-scs'
 INFO: Load project settings for component key: 'serviceweb-scs' (done) | time=17ms
 INFO: Load project branches
 INFO: Load project branches (done) | time=37ms
 INFO: Load project pull requests
 INFO: Load project pull requests (done) | time=12ms
 INFO: Load branch configuration
 INFO: Load branch configuration (done) | time=1ms
 INFO: Load quality profiles
 INFO: Load quality profiles (done) | time=47ms
 INFO: Detected Gitlab CI
 INFO: Load active rules
 INFO: Load active rules (done) | time=607ms
 INFO: Branch name: 20.1-pnp_SPB_MB
 INFO: Indexing files...
 INFO: Project configuration:
 INFO:   Included sources: **/BL.js, **/BL*.js, **/BL.ts, **/BL*.ts
 INFO:   Excluded sources: src/**/lang/**, src/app/configs/routeConfigs/settingsConfig/**, src/host/public/static/tap2join/**, src/RCLibX/**, src/mobile/**, src/desktop/**, **/*.spec.js, **/*.spec.ts, **/BL.spec.js, **/BL*.spec.js, **/BL.spec.ts, **/BL*.spec.ts
 INFO:   Included tests: **/BL.spec.js, **/BL*.spec.js, **/BL.spec.ts, **/BL*.spec.ts
 INFO: Load project repositories
 INFO: Load project repositories (done) | time=19ms
 INFO: 143 files indexed
 INFO: 0 files ignored because of inclusion/exclusion patterns
 INFO: 0 files ignored because of scm ignore settings
 INFO: Quality profile for js: Sonar way Recommended
 INFO: Quality profile for ts: Sonar way recommended
 INFO: ------------- Run sensors on module ServiceWeb RCWeb
 INFO: Load metrics repository
 INFO: Load metrics repository (done) | time=18ms
 WARNING: An illegal reflective access operation has occurred
 WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (file:/builds/web/web/.sonar/cache/xxx/sonar-javascript-plugin.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
 WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$1
 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
 WARNING: All illegal access operations will be denied in a future release
 INFO: Sensor SonarCSS Rules [cssfamily]
 INFO: No CSS, PHP, HTML or VueJS files are found in the project. CSS analysis is skipped.
 INFO: Sensor SonarCSS Rules [cssfamily] (done) | time=3ms
 INFO: Sensor JaCoCo XML Report Importer [jacoco]
 INFO: 'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
 INFO: No report imported, no coverage information will be imported by JaCoCo XML Report Importer
 INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=3ms
 INFO: Sensor JavaScript analysis [javascript]
 INFO: Using TypeScript at: '/builds/web/web/.yarn/unplugged/typescript-patch-c624345536/node_modules'
 INFO: 48 source files to be analyzed
 WARN: locking FileBasedConfig[/root/.config/jgit/config] failed after 5 retries
 INFO: 48/48 source files have been analyzed
 INFO: Sensor SonarJS [javascript]
 INFO: 48 source files to be analyzed
 INFO: Sensor SonarJS [javascript] (done) | time=4377ms
 INFO: Sensor JavaScript analysis [javascript] (done) | time=13805ms
 INFO: Sensor SonarJS Coverage [javascript]
 WARN: The use of sonar.typescript.lcov.reportPaths for coverage import is deprecated, use sonar.javascript.lcov.reportPaths instead.
 INFO: 48/48 source files have been analyzed
 INFO: Analysing [/builds/web/web/src/visualIVR/coverage/lcov.info, /builds/web/web/src/app/coverage/lcov.info]
 WARN: Could not resolve 4003 file paths in [/builds/web/web/src/visualIVR/coverage/lcov.info, /builds/web/web/src/app/coverage/lcov.info]
 WARN: First unresolved path: build-config.js (Run in DEBUG mode to get full list of unresolved paths)
 INFO: Sensor SonarJS Coverage [javascript] (done) | time=162ms
 INFO: Sensor TypeScript analysis [javascript]
 INFO: Using /builds/web/web/tsconfig.json from sonar.typescript.tsconfigPath property
 INFO: 57 source files to be analyzed
 INFO: Analyzing 57 files using tsconfig: /builds/web/web/tsconfig.json
 WARN: You are using version of TypeScript 3.8.3 which is not officially supported; supported versions >=3.2.1 <3.8.0
 INFO: 0/57 files analyzed, current file: src/modules/src/extensionSettings/BL.ts
 INFO: 0/57 files analyzed, current file: src/modules/src/extensionSettings/BL.ts
 ERROR: Failed to analyze file [src/modules/src/extensionSettings/BL.ts]: File 'web-modules-build/src/typescript/tsconfig' not found.
 INFO: 1/57 files analyzed, current file: src/app/modules/upgradeWizards/BL.ts
 INFO: 1/57 files analyzed, current file: src/app/modules/upgradeWizards/BL.ts
 INFO: 1/57 files analyzed, current file: src/app/modules/upgradeWizards/BL.ts
 ERROR: Failed to analyze file [src/app/modules/upgradeWizards/BL.ts]: File 'web-modules-build/src/typescript/tsconfig' not found.
 INFO: 2/57 files analyzed, current file: src/app/modules/gateway/components/common/BL.ts
 INFO: 2/57 files analyzed, current file: src/app/modules/gateway/components/common/BL.ts
 ERROR: Failed to analyze file [src/app/modules/gateway/components/common/BL.ts]: File 'web-modules-build/src/typescript/tsconfig' not found.
 INFO: 3/57 files analyzed, current file: src/app/modules/lboShelf/BL.ts
 INFO: 3/57 files analyzed, current file: src/app/modules/lboShelf/BL.ts
 INFO: 3/57 files analyzed, current file: src/app/modules/lboShelf/BL.ts
 ERROR: Failed to analyze file [src/app/modules/lboShelf/BL.ts]: File 'web-modules-build/src/typescript/tsconfig' not found.
 INFO: 4/57 files analyzed, current file: src/modules/src/meetings/BL.ts
 INFO: 4/57 files analyzed, current file: src/modules/src/meetings/BL.ts
 ERROR: Failed to analyze file [src/modules/src/meetings/BL.ts]: File 'web-modules-build/src/typescript/tsconfig' not found.
 INFO: 5/57 files analyzed, current file: src/app/modules/hostLayout/helpers/BL.ts
 INFO: 5/57 files analyzed, current file: src/app/modules/hostLayout/helpers/BL.ts
 INFO: 5/57 files analyzed, current file: src/app/modules/hostLayout/helpers/BL.ts
 ERROR: Failed to analyze file [src/app/modules/hostLayout/helpers/BL.ts]: File 'web-modules-build/src/typescript/tsconfig' not found.
 INFO: 6/57 files analyzed, current file: src/modules/src/userGroups/BL.ts
 INFO: 6/57 files analyzed, current file: src/modules/src/userGroups/BL.ts
 INFO: 6/57 files analyzed, current file: src/modules/src/userGroups/BL.ts
 ERROR: Failed to analyze file [src/modules/src/userGroups/BL.ts]: File 'web-modules-build/src/typescript/tsconfig' not found.
 INFO: 7/57 files analyzed, current file: src/app/modules/numbers/BL.ts
 INFO: 7/57 files analyzed, current file: src/app/modules/numbers/BL.ts
 INFO: 7/57 files analyzed, current file: src/app/modules/numbers/BL.ts
 ERROR: Failed to analyze file [src/app/modules/numbers/BL.ts]: File 'web-modules-build/src/typescript/tsconfig' not found.
 INFO: 8/57 files analyzed, current file: src/modules/src/ivrMenu/BL.ts
 INFO: 8/57 files analyzed, current file: src/modules/src/ivrMenu/BL.ts
 INFO: 8/57 files analyzed, current file: src/modules/src/ivrMenu/BL.ts
 INFO: 8/57 files analyzed, current file: src/modules/src/ivrMenu/BL.ts
 ERROR: Failed to analyze file [src/modules/src/ivrMenu/BL.ts]: File 'web-modules-build/src/typescript/tsconfig' not found.
 INFO: 9/57 files analyzed, current file: src/modules/src/delegates/BL.ts
 INFO: 9/57 files analyzed, current file: src/modules/src/delegates/BL.ts
 INFO: 9/57 files analyzed, current file: src/modules/src/delegates/BL.ts
 INFO: 9/57 files analyzed, current file: src/modules/src/delegates/BL.ts
 ERROR: Failed to analyze file [src/modules/src/delegates/BL.ts]: File 'web-modules-build/src/typescript/tsconfig' not found.
 INFO: 10/57 files analyzed, current file: src/modules/src/common/BL.ts
 INFO: 10/57 files analyzed, current file: src/modules/src/common/BL.ts
 INFO: 10/57 files analyzed, current file: src/modules/src/common/BL.ts
 INFO: 10/57 files analyzed, current file: src/modules/src/common/BL.ts
 INFO: 10/57 files analyzed, current file: src/modules/src/common/BL.ts
 INFO: 10/57 files analyzed, current file: src/modules/src/common/BL.ts
 ERROR: eslint-bridge Node.js process is unresponsive. This is most likely caused by process running out of memory. Consider setting sonar.javascript.node.maxspace to higher value (e.g. 4096).
 INFO: Sensor TypeScript analysis [javascript] (done) | time=354682ms
 ERROR: Failure during analysis, Node.js command to start eslint-bridge was: {NODE_PATH=/builds/web/web/.yarn/unplugged/typescript-patch-c624345536/node_modules} node /builds/web/web/.scannerwork/.sonartmp/eslint-bridge-bundle/package/bin/server 32801
 java.lang.IllegalStateException: eslint-bridge is unresponsive
 	at org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl.request(EslintBridgeServerImpl.java:202)
 	at org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl.analyzeTypeScript(EslintBridgeServerImpl.java:186)
 	at org.sonar.plugins.javascript.eslint.TypeScriptSensor.analyze(TypeScriptSensor.java:153)
 	at org.sonar.plugins.javascript.eslint.TypeScriptSensor.analyzeFilesWithTsConfig(TypeScriptSensor.java:141)
 	at org.sonar.plugins.javascript.eslint.TypeScriptSensor.analyzeFiles(TypeScriptSensor.java:121)
 	at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.execute(AbstractEslintSensor.java:107)
 	at org.sonar.plugins.javascript.eslint.TypeScriptSensor.execute(TypeScriptSensor.java:53)
 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:386)
 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:382)
 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:351)
 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
 Caused by: java.io.InterruptedIOException: timeout
 	at okhttp3.RealCall.timeoutExit(RealCall.java:108)
 	at okhttp3.RealCall.execute(RealCall.java:97)
 	at org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl.request(EslintBridgeServerImpl.java:195)
 	... 36 common frames omitted
 Caused by: java.io.IOException: Canceled
 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:119)
 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
 	at okhttp3.RealCall.execute(RealCall.java:93)
 	... 37 common frames omitted
 INFO: Sensor JavaXmlSensor [java]
 INFO: Sensor JavaXmlSensor [java] (done) | time=2ms
 INFO: Sensor HTML [web]
 INFO: Sensor HTML [web] (done) | time=4ms
 INFO: Sensor SonarTS [typescript]
 INFO: Since SonarTS v2.0, TypeScript analysis is performed by SonarJS analyzer v6.0 or later. No TypeScript analysis is performed by SonarTS.
 INFO: Sensor SonarTS [typescript] (done) | time=0ms
 INFO: Sensor com.github.mc1arke.sonarqube.plugin.scanner.ScannerPullRequestPropertySensor
 INFO: Sensor com.github.mc1arke.sonarqube.plugin.scanner.ScannerPullRequestPropertySensor (done) | time=3ms
 INFO: ------------- Run sensors on project
 INFO: Sensor Zero Coverage Sensor
 INFO: Sensor Zero Coverage Sensor (done) | time=3ms
 INFO: SCM Publisher SCM provider for this project is: git
 INFO: SCM Publisher 2 source files to be analyzed
 INFO: SCM Publisher 2/2 source files have been analyzed (done) | time=1808ms
 INFO: CPD Executor 1 file had no CPD blocks
 INFO: CPD Executor Calculating CPD for 47 files
 INFO: CPD Executor CPD calculation finished (done) | time=78ms
 INFO: Analysis report generated in 109ms, dir size=2 MB
 INFO: Analysis report compressed in 313ms, zip size=736 KB
 INFO: Analysis report uploaded in 160ms
 INFO: ANALYSIS SUCCESSFUL, you can browse https://xxx/dashboard?id=serviceweb-scs&branch=20.1-pnp_SPB_MB
 INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
 INFO: More about the report processing at https://xxx/api/ce/task?id=AXNuLYX13pxbwB6meayk
 ERROR: eslint-bridge Node.js process is unresponsive. This is most likely caused by process running out of memory. Consider setting sonar.javascript.node.maxspace to higher value (e.g. 4096).
 WARN: Stopping of component org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl failed
 java.lang.IllegalStateException: eslint-bridge is unresponsive
 	at org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl.request(EslintBridgeServerImpl.java:202)
 	at org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl.clean(EslintBridgeServerImpl.java:283)
 	at org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl.stop(EslintBridgeServerImpl.java:308)
 	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.stop(StartableCloseableSafeLifecyleStrategy.java:52)
 	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.stop(AbstractInjectionFactory.java:88)
 	at org.picocontainer.behaviors.AbstractBehavior.stop(AbstractBehavior.java:179)
 	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.stop(Stored.java:141)
 	at org.picocontainer.behaviors.Stored.stop(Stored.java:118)
 	at org.picocontainer.DefaultPicoContainer.stopAdapters(DefaultPicoContainer.java:1048)
 	at org.picocontainer.DefaultPicoContainer.stop(DefaultPicoContainer.java:803)
 	at org.sonar.core.platform.ComponentContainer.stopComponents(ComponentContainer.java:165)
 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:124)
 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
 Caused by: java.io.InterruptedIOException: timeout
 	at okhttp3.RealCall.timeoutExit(RealCall.java:108)
 	at okhttp3.RealCall.execute(RealCall.java:97)
 	at org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl.request(EslintBridgeServerImpl.java:195)
 	... 28 common frames omitted
 Caused by: java.net.SocketTimeoutException: timeout
 	at okio.Okio$4.newTimeoutException(Okio.java:232)
 	at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
 	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:226)
 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:202)
 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:101)
 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
 	at okhttp3.RealCall.execute(RealCall.java:93)
 	... 29 common frames omitted
 Caused by: java.net.SocketException: Socket closed
 	at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:249)
 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:328)
 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:351)
 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:802)
 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:919)
 	at okio.Okio$2.read(Okio.java:140)
 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
 	... 48 common frames omitted
 INFO: Analysis total time: 7:17.197 s
 INFO: ------------------------------------------------------------------------
 INFO: EXECUTION SUCCESS
 INFO: ------------------------------------------------------------------------
 INFO: Total time: 7:18.416s
 INFO: Final Memory: 16M/67M
 INFO: ------------------------------------------------------------------------
```

First, each file takes about a minute to process, and as a result job cannot be completed and fails with out of memory error. I tried to give process more memory by doing following in the `.gitlab-ci.yml`:

```
sonarqube:
  stage: deploy
  name: sonarsource/sonar-scanner-cli:latest
  entrypoint: ['']
  variables:
    NODE_OPTIONS: --max-old-space-size=12228
    GIT_DEPTH: 0
  script:
    - sonar-scanner -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
```

**Comment by kirill-konshin** [comment]
I have tried both `NODE_OPTIONS: --max-old-space-size=12228` and `sonar.javascript.node.maxspace=12228`, neither has any effect.

**Comment by saberduck** [comment]
hello @kirill-konshin , how much memory is available to the container running the analysis? which version of node do you use?

**Comment by kirill-konshin** [comment]
CI machine has 32gb of memory, Node is 13.8.0

**Comment by vilchik-elena** [comment]
from logs I see that you force the use of some tsconfig, as each file analysis fails with the message that this tsconfig is not found. May be perf problem is related to that somehow?

**Comment by kirill-konshin** [comment]
This could be related to Yarn in PNP mode. It does work in normal build but seems that Sonar is improperly resolving `extends` in `tsconfig.json`:

```json
{
  "extends": "web-modules-build/src/typescript/tsconfig.json",
  ...
}
```

`web-modules-build` is a part of monorepo.

**Comment by georgelviv** [comment]
Maybe for someone will be helpful
https://github.com/SonarSource/SonarJS/issues/1960#issuecomment-686369991

**Comment by saberduck** [comment]
We released new version as part of SonarQube 8.5, can you give it a try to see if you still have this issue? There were couple of fixes targeting the performance and parsing of `tsconfig.json` files.

**Comment by saberduck** [comment]
Since there is no more activity on this issue, I will close it. Feel free to submit new issue if you have problem with the latest version.

**Comment by kirill-konshin** [comment]
@saberduck the ball was on your side actually.

**Comment by saberduck** [comment]
@kirill-konshin sorry if I didn't understand the situation. Feel free to create a new issue if you face a problem using the latest version.
