### ISSUE TITLE
Support TypeScript 5

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#3770]

**Comment by josundt** [comment]
Please fix

**Comment by LukaPrebil** [comment]
TS5 introduced the option to extend tsconfig from multiple files. This breaks the sonar scanner.

```json
{
  "extends": [
    "@tsconfig/node18/tsconfig.json",
    "@tsconfig/strictest/tsconfig.json"
  ]
}
```

```
ERROR: Error: Compiler option 'extends' requires a value of type string.
ERROR:     at createProgramOptions (/github/workspace/.scannerwork/.sonartmp/eslint-bridge-bundle/package/lib/services/program/program.js:106:15)
ERROR:     at createProgram (/github/workspace/.scannerwork/.sonartmp/eslint-bridge-bundle/package/lib/services/program/program.js:132:28)
ERROR:     at default_1 (/github/workspace/.scannerwork/.sonartmp/eslint-bridge-bundle/package/lib/routing/on-create-program.js:10:57)
ERROR:     at Layer.handle [as handle_request] (/github/workspace/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/express/lib/router/layer.js:95:5)
ERROR:     at next (/github/workspace/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/express/lib/router/route.js:144:13)
ERROR:     at Route.dispatch (/github/workspace/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/express/lib/router/route.js:114:3)
ERROR:     at Layer.handle [as handle_request] (/github/workspace/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/express/lib/router/layer.js:95:5)
ERROR:     at /github/workspace/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/express/lib/router/index.js:284:15
ERROR:     at Function.process_params (/github/workspace/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/express/lib/router/index.js:346:12)
ERROR:     at next (/github/workspace/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/express/lib/router/index.js:280:10)
ERROR: Failed to create program: Compiler option 'extends' requires a value of type string.
```
