### ISSUE TITLE
Should not include special characters in issue message

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3931]
We should not include special characters in the issue message, because they are not allowed by Sonar APIs

```
ERROR: Failed to get response while analyzing file:///tmp/cirrus-ci-build/nextjs/workspace/packages/next-swc/crates/next-dev-tests/tests/integration/turbopack/basic/error/input/broken.js
java.lang.IllegalArgumentException: Character \u0000 is not supported in issue message 'Unexpected character ''. (1:0)'
	at org.sonar.api.batch.sensor.issue.internal.DefaultIssueLocation.validateMessage(DefaultIssueLocation.java:104)
	at org.sonar.api.batch.sensor.issue.internal.DefaultIssueLocation.message(DefaultIssueLocation.java:67)
	at org.sonar.api.batch.sensor.issue.internal.DefaultIssueLocation.message(DefaultIssueLocation.java:40)
	at org.sonar.plugins.javascript.eslint.AnalysisProcessor.processParsingError(AnalysisProcessor.java:157)
	at org.sonar.plugins.javascript.eslint.AnalysisProcessor.processResponse(AnalysisProcessor.java:94)
	at org.sonar.plugins.javascript.eslint.JsTsSensor.analyze(JsTsSensor.java:107)
	at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.analyzeFiles(AbstractEslintSensor.java:130)
	at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.execute(AbstractEslintSensor.java:79)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
```

Failing peach projects are `nextjs` and `regexp-corpus` , special characters should be escaped before

**Comment by JithilNCA** [comment]
Is there any recommendation to replicate this issue?

Fan of `good first issues` .

**Comment by saberduck** [comment]
see also https://sonarsource.atlassian.net/browse/SONAR-13615 

@JithilNCA sorry, I don't think this is a good first issue
