### ISSUE TITLE
Add support for Sass syntax

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#4221]
The CSS analyzer does not support the [Sass](https://sass-lang.com/) syntax. Currently, if we try to analyze such syntax from `.sass` files or from the script section (`<script lang="sass">`) of Vue.js single file components, the analysis fails with the following error:

```
INFO: Sensor CSS Rules [javascript]
INFO: X source files to be analyzed
ERROR: Error: Cannot find module 'postcss-sass'
ERROR: Require stack:
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss-syntax/get-syntax.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss-syntax/parser.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss-syntax/parse.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss-syntax/index.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/stylelint/lib/getPostcssResult.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/stylelint/lib/lintSource.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/stylelint/lib/postcssPlugin.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/stylelint/lib/index.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/lib/css/src/linter/wrapper.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/lib/css/src/linter/index.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/lib/css/src/analysis/analyzer.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/lib/css/src/analysis/index.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/lib/css/src/index.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/lib/bridge/src/router/on-analyze-css.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/lib/bridge/src/router/index.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/lib/bridge/src/server.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/lib/server.js
ERROR: - /some/project/.scannerwork/.sonartmp/bridge-bundle/package/bin/server
ERROR:     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
ERROR:     at Module._resolveFilename (/some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/module-alias/index.js:49:29)
ERROR:     at Module._load (node:internal/modules/cjs/loader:922:27)
ERROR:     at Module.require (node:internal/modules/cjs/loader:1143:19)
ERROR:     at require (node:internal/modules/cjs/helpers:121:18)
ERROR:     at requireSyntax (/some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss-syntax/get-syntax.js:31:19)
ERROR:     at getSyntax (/some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss-syntax/get-syntax.js:50:10)
ERROR:     at parser (/some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss-syntax/parser.js:9:17)
ERROR:     at Function.parse (/some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss-syntax/parse.js:28:10)
ERROR:     at new LazyResult (/some/project/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss/lib/lazy-result.js:133:16)
```

Since the CSS analyzer uses Stylelint behind the scenes, adding support for Sass should be straightforward. All that needs to be done should be adding and bundling the [postcss-sass](https://www.npmjs.com/package/postcss-sass) dependency as we did for other syntaxes:

https://github.com/SonarSource/SonarJS/blob/c7d9904769000b6498affab877fc51dd0c683f4a/package.json#L92-L95

The analyzer's documentation should be updated accordingly. SonarJS's README should mention Sass support. This change should then be communicated to the documentation team so that SonarQube and SonarCloud documentations are updated as well.

Reported in https://community.sonarsource.com/t/error-cannot-find-module-postcss-sass-while-launching-the-scan-from-github-action/101289

**Comment by jraez** [comment]
+1

ignoring .sass in css configuration "works" if you use plain sass files only (but they are not scanned, obvisouly). 
If you have style in your compoment, it'll crash no matter the configuration.

**Comment by yassin-kammoun-sonarsource** [comment]
Indeed.

And for the record, by default, ".sass" files are not picked by the analyzer. However, if you configure the scanner with the property `sonar.css.file.suffixes=.sass`. It will also crash the very same way :/

**Comment by jraez** [comment]
You are right, we went from "included" to "excluded" to be cautious. But simply not include them is enough.
