### ISSUE TITLE
Fix CSS rule S4666 (`no-duplicate-selectors`): Should not crash when using sass

### ISSUE THREAD

**Issue by vdiez** [SonarSource/SonarJS#4449]
Reported in community: https://community.sonarsource.com/t/sonar-is-returning-an-error-when-analyzing-sass-files/104926

Error stack: 
```
19:11:21.557 DEBUG: Analyzing file: file:///usr/src/app/styles/editor/helpers/spacing.sass
19:11:21.564 ERROR: Error: The node source must be present
19:11:21.564 ERROR:     at Object.getContext (/usr/src/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/stylelint/lib/utils/nodeContextLookup.js:23:28)
19:11:21.564 ERROR:     at /usr/src/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/stylelint/lib/rules/no-duplicate-selectors/index.js:60:53
19:11:21.564 ERROR:     at /usr/src/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss/lib/container.js:369:18
19:11:21.564 ERROR:     at /usr/src/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss/lib/container.js:297:18
19:11:21.564 ERROR:     at Root.each (/usr/src/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss/lib/container.js:53:16)
19:11:21.564 ERROR:     at Root.walk (/usr/src/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss/lib/container.js:294:17)
19:11:21.564 ERROR:     at Root.walkRules (/usr/src/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/postcss/lib/container.js:367:19)
19:11:21.564 ERROR:     at /usr/src/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/stylelint/lib/rules/no-duplicate-selectors/index.js:55:8
19:11:21.564 ERROR:     at /usr/src/.scannerwork/.sonartmp/bridge-bundle/package/node_modules/stylelint/lib/lintPostcssResult.js:120:8
19:11:21.564 ERROR:     at Array.map (<anonymous>)
19:11:21.565 DEBUG: Found 0 issue(s)
```

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-50
