### ISSUE TITLE
maximumLineLength duplice key

### ISSUE THREAD

**Issue by comdata** [SonarSource/SonarJS#971]
**SonarJS version:** 4.1
**SonarQube version:** 7.1

**Rule key:** 

maximumLineLength

**Reproducer** 

have the plugin installed and restart the Sonarqube instance. Removing the plugin makes the issue go away.

**Logs**
```
2018.04.23 08:22:37 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalArgumentException: Duplicate key maximumLineLength
        at org.sonar.core.util.stream.MoreCollectors.putAndFailOnDuplicateKey(MoreCollectors.java:295)
        at org.sonar.core.util.stream.MoreCollectors.lambda$uniqueIndex$9(MoreCollectors.java:256)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.sonar.server.qualityprofile.RuleActivationContext$RuleWrapper.<init>(RuleActivationContext.java:282)
        at org.sonar.server.qualityprofile.RuleActivationContext$RuleWrapper.<init>(RuleActivationContext.java:276)
        at org.sonar.server.qualityprofile.RuleActivationContext.<init>(RuleActivationContext.java:90)
        at org.sonar.server.qualityprofile.RuleActivationContext.<init>(RuleActivationContext.java:55)
        at org.sonar.server.qualityprofile.RuleActivationContext$Builder.build(RuleActivationContext.java:272)
        at org.sonar.server.qualityprofile.RuleActivator.createContextForBuiltInProfile(RuleActivator.java:381)
        at org.sonar.server.qualityprofile.BuiltInQProfileUpdateImpl.update(BuiltInQProfileUpdateImpl.java:61)
        at org.sonar.server.qualityprofile.RegisterQualityProfiles.update(RegisterQualityProfiles.java:118)
        at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$start$1(RegisterQualityProfiles.java:85)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.sonar.server.qualityprofile.RegisterQualityProfiles.start(RegisterQualityProfiles.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:134)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:44)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:81)
        at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:78)
        at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:196)
        at org.sonar.server.platform.Platform.access$400(Platform.java:46)
        at org.sonar.server.platform.Platform$1.lambda$doRun$1(Platform.java:121)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
        at org.sonar.server.platform.Platform$1.doRun(Platform.java:121)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
        at java.lang.Thread.run(Thread.java:748)
2018.04.23 08:22:37 INFO  web[][o.s.p.StopWatcher] Stopping process

```

**Expected behavior**

Sonarqube starts without any issues.

**Comment by comdata** [comment]
sorry for the delay. please find attached the logs:
[logs.zip](https://github.com/SonarSource/SonarJS/files/1982853/logs.zip)

**Comment by simonbrandhof** [comment]
Thanks. I managed to reproduce. The bug will be fixed in SonarQube 7.2 (https://jira.sonarsource.com/browse/SONAR-10663). Meanwhile you should manually clean-up the db table `rules_parameters`. The details are provided in the ticket.

Sorry for the inconvenience.

**Comment by comdata** [comment]
the initial error came when upgrading from 6.2 I think. The installation is already older and upgraded from at least 5.x.
For the last upgrade I went to the update center before and updated all plugins to the highest version and restarted. Afterward I went ahead upgrading Sonarqube.

**Comment by comdata** [comment]
found the following duplicates in my system here:
 rule_id |       name        | count
---------+-------------------+-------
      17 | regularExpression |     4
      17 | message           |     4
     102 | regularExpression |     5
     102 | message           |     5
      48 | maximumLineLength |     5
     454 | regularExpression |     4
     454 | message           |     4
    2073 | regularExpression |     5
    2073 | message           |     5
    1292 | maximumLineLength |     4
    1359 | regularExpression |     4
    1359 | message           |     4
    2007 | maximumLineLength |     4
     241 | maximumLineLength |     5
    1372 | maximumLineLength |     9
    3027 | maximumLineLength |     9
    1447 | regularExpression |     8
    1447 | message           |     8

**Comment by comdata** [comment]
tried deleting the rules and then readding the plugin but still get the same error. I suspect the rules a reloaded during the restart.

**Comment by simonbrandhof** [comment]
just to be sure, executing `SELECT rule_id, name, count(name) FROM public.rules_parameters group by rule_id, name having count(name)>1` returned empty before restarting ?

**Comment by comdata** [comment]
Yes. It did.

**Comment by simonbrandhof** [comment]
I managed to reproduce the error when rows are duplicated in db but I don't manage to generate these duplications. The logs you provided do not show an upgrade of SonarQube, so the scenario has probably been a bit different. 

I suggest to close this issue, the problem does not come from SonarJS itself. In the current state I don't think that we will be able to fix the root pb in https://jira.sonarsource.com/browse/SONAR-10663, but at least I hope it will help investigating.

**Comment by comdata** [comment]
just a short update, I deleted all contents from the rules* tables and this seemed to do the trick so far.
